[database]
url = "supabase_url"

api_key = "supabase_api_key"


[openai]

openai_api_key = "openai_api_key"

[cockroachdb]

connection_string = "crdb_conn_sting"

rss_links_table_name = "rss_links"

website_table_name = "rss_feed_websites"

[rssReaderConfig]

chunk_size = 10

days_to_crawl = 1

[sentimentModel]

sentiment_model = "cardiffnlp/twitter-roberta-base-sentiment-latest"